package com.technologica.registration.deferred;

import com.technologica.Technologica;
import com.technologica.world.level.material.ArgonFluid;
import com.technologica.world.level.material.BrineFluid;
import com.technologica.world.level.material.BromineFluid;
import com.technologica.world.level.material.ChlorineFluid;
import com.technologica.world.level.material.CoolantFluid;
import com.technologica.world.level.material.FluorineFluid;
import com.technologica.world.level.material.GasolineFluid;
import com.technologica.world.level.material.HeliumFluid;
import com.technologica.world.level.material.HydrogenFluid;
import com.technologica.world.level.material.KryptonFluid;
import com.technologica.world.level.material.MachineOilFluid;
import com.technologica.world.level.material.MapleSyrupFluid;
import com.technologica.world.level.material.MercuryFluid;
import com.technologica.world.level.material.MoltenCoreFluid;
import com.technologica.world.level.material.NaturalGasFluid;
import com.technologica.world.level.material.NeonFluid;
import com.technologica.world.level.material.NitrogenFluid;
import com.technologica.world.level.material.OilFluid;
import com.technologica.world.level.material.OxygenFluid;
import com.technologica.world.level.material.RadonFluid;
import com.technologica.world.level.material.RubberResinFluid;
import com.technologica.world.level.material.XenonFluid;

import net.minecraft.world.level.material.FlowingFluid;
import net.minecraftforge.registries.RegistryObject;

public final class TechnologicaFluids {
	public static final RegistryObject<FlowingFluid> FLOWING_HYDROGEN = Technologica.FLUIDS.register("flowing_hydrogen", HydrogenFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> HYDROGEN = Technologica.FLUIDS.register("hydrogen", HydrogenFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_HELIUM = Technologica.FLUIDS.register("flowing_helium", HeliumFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> HELIUM = Technologica.FLUIDS.register("helium", HeliumFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_NITROGEN = Technologica.FLUIDS.register("flowing_nitrogen", NitrogenFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> NITROGEN = Technologica.FLUIDS.register("nitrogen", NitrogenFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_OXYGEN = Technologica.FLUIDS.register("flowing_oxygen", OxygenFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> OXYGEN = Technologica.FLUIDS.register("oxygen", OxygenFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_FLUORINE = Technologica.FLUIDS.register("flowing_fluorine", FluorineFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> FLUORINE = Technologica.FLUIDS.register("fluorine", FluorineFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_NEON = Technologica.FLUIDS.register("flowing_neon", NeonFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> NEON = Technologica.FLUIDS.register("neon", NeonFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_CHLORINE = Technologica.FLUIDS.register("flowing_chlroine", ChlorineFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> CHLORINE = Technologica.FLUIDS.register("chlorine", ChlorineFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_ARGON = Technologica.FLUIDS.register("flowing_argon", ArgonFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> ARGON = Technologica.FLUIDS.register("argon", ArgonFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_KRYPTON = Technologica.FLUIDS.register("flowing_krypton", KryptonFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> KRYPTON = Technologica.FLUIDS.register("krypton", KryptonFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_XENON = Technologica.FLUIDS.register("flowing_xenon", XenonFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> XENON = Technologica.FLUIDS.register("xenon", XenonFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_RADON = Technologica.FLUIDS.register("flowing_radon", RadonFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> RADON = Technologica.FLUIDS.register("radon", RadonFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_BROMINE = Technologica.FLUIDS.register("flowing_bromine", BromineFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> BROMINE = Technologica.FLUIDS.register("bromine", BromineFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_MERCURY = Technologica.FLUIDS.register("flowing_mercury", MercuryFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> MERCURY = Technologica.FLUIDS.register("mercury", MercuryFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_BRINE = Technologica.FLUIDS.register("flowing_brine", BrineFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> BRINE = Technologica.FLUIDS.register("brine", BrineFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_OIL = Technologica.FLUIDS.register("flowing_oil", OilFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> OIL = Technologica.FLUIDS.register("oil", OilFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_NATURAL_GAS = Technologica.FLUIDS.register("flowing_natural_gas", NaturalGasFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> NATURAL_GAS = Technologica.FLUIDS.register("natural_gas", NaturalGasFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_MAPLE_SYRUP = Technologica.FLUIDS.register("flowing_maple_syrup", MapleSyrupFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> MAPLE_SYRUP = Technologica.FLUIDS.register("maple_syrup", MapleSyrupFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_RUBBER_RESIN = Technologica.FLUIDS.register("flowing_rubber_resin", RubberResinFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> RUBBER_RESIN = Technologica.FLUIDS.register("rubber_resin", RubberResinFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_GASOLINE = Technologica.FLUIDS.register("flowing_gasoline", GasolineFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> GASOLINE = Technologica.FLUIDS.register("gasoline", GasolineFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_MACHINE_OIL = Technologica.FLUIDS.register("flowing_machine_oil", MachineOilFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> MACHINE_OIL = Technologica.FLUIDS.register("machine_oil", MachineOilFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_COOLANT = Technologica.FLUIDS.register("flowing_coolant", CoolantFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> COOLANT = Technologica.FLUIDS.register("coolant", CoolantFluid.Source::new);
	public static final RegistryObject<FlowingFluid> FLOWING_MOLTEN_CORE = Technologica.FLUIDS.register("flowing_molten_core", MoltenCoreFluid.Flowing::new);
	public static final RegistryObject<FlowingFluid> MOLTEN_CORE = Technologica.FLUIDS.register("molten_core", MoltenCoreFluid.Source::new);
}
