modLoader="javafml"
loaderVersion="[35,)"
logoFile="modconfiggraphic.png"
license="All rights reserved"

[[mods]]
	modId="technologica"
	version="1.0.0"
	displayName="Technologica"
	
	credits="Basically just us"
	authors="The Phantom, Queen Seeker, Linehart1"
	description='''
    Anything and everything we want.
    
    But mostly just fruits right now.
    
    Fruits and some ingots.
    '''
[[dependencies.technologica]] 
    modId="forge" 
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technologica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"