package com.technologica.registration.dynamic;

import com.technologica.Technologica;
import com.tlregen.api.resourcegen.util.helpers.TLReGenDimensionHelper;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.dimension.LevelStem;

public final class TechnologicaDimensions {
	public static final ResourceKey<LevelStem> MOON_STEM = Technologica.DIMENSIONS.register("moon", () -> TLReGenDimensionHelper.dimension(TechnologicaDimensionTypes.MOON, TLReGenDimensionHelper.chunkGenerator("noise", new TLReGenDimensionHelper.BiomeSourceBuilder("multi_noise").add(TLReGenDimensionHelper.biome(TechnologicaBiomes.SILENT_EXPANSES, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.CRATER_FIELDS, TLReGenDimensionHelper.parameters(-1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.SHATTERED_CORRIDORS, TLReGenDimensionHelper.parameters(1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F))).build(), TechnologicaNoiseGeneratorSettings.MOON)));
	public static final ResourceKey<LevelStem> ABYSS_STEM = Technologica.DIMENSIONS.register("abyss", () -> TLReGenDimensionHelper.dimension(TechnologicaDimensionTypes.ABYSS, TLReGenDimensionHelper.chunkGenerator("noise", new TLReGenDimensionHelper.BiomeSourceBuilder("multi_noise").add(TLReGenDimensionHelper.biome(TechnologicaBiomes.RUSTING_GROUNDS, TLReGenDimensionHelper.parameters(0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.5F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.FORGOTTEN_REEF, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.5F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.NAVAL_GRAVEYARD, TLReGenDimensionHelper.parameters(0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.SUNKEN_FOREST, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.HYDROTHERMAL_CAVERN, TLReGenDimensionHelper.parameters(0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.ECHOSCAPE, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F))).build(), TechnologicaNoiseGeneratorSettings.ABYSS)));
	public static final ResourceKey<LevelStem> OVERGROWTH_STEM = Technologica.DIMENSIONS.register("overgrowth", () -> TLReGenDimensionHelper.dimension(TechnologicaDimensionTypes.OVERGROWTH, TLReGenDimensionHelper.chunkGenerator("noise", new TLReGenDimensionHelper.BiomeSourceBuilder("multi_noise").add(TLReGenDimensionHelper.biome(TechnologicaBiomes.MISTY_MIRE, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F))).add(TLReGenDimensionHelper.biome(TechnologicaBiomes.BRAMBLE, TLReGenDimensionHelper.parameters(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F))).build(), TechnologicaNoiseGeneratorSettings.OVERGROWTH)));
}
