package com.technologica.registration.dynamic;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.technologica.Technologica;
import com.technologica.registration.deferred.TechnologicaBlocks;
import com.technologica.world.level.levelgen.placement.BoundedHeightmap;
import com.tlregen.api.resourcegen.data.worldgen.TLReGenWorldgenPlacedFeature;

import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.features.AquaticFeatures;
import net.minecraft.data.worldgen.features.TreeFeatures;
import net.minecraft.data.worldgen.features.VegetationFeatures;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.valueproviders.ConstantInt;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.levelgen.VerticalAnchor;
import net.minecraft.world.level.levelgen.placement.BiomeFilter;
import net.minecraft.world.level.levelgen.placement.CountOnEveryLayerPlacement;
import net.minecraft.world.level.levelgen.placement.CountPlacement;
import net.minecraft.world.level.levelgen.placement.HeightRangePlacement;
import net.minecraft.world.level.levelgen.placement.InSquarePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.levelgen.placement.PlacementModifier;
import net.minecraft.world.level.levelgen.placement.RarityFilter;
import net.minecraft.world.level.levelgen.placement.SurfaceWaterDepthFilter;

@SuppressWarnings("deprecation")
public final class TechnologicaPlacedFeatures {
	// static Holder<ConfiguredFeature<?, ?>> TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLACKBERRY_BUSH) = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLACKBERRY_BUSH);
	// static Holder<ConfiguredFeature<?, ?>> patchBlueberryBush = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLUEBERRY_BUSH);
	// static Holder<ConfiguredFeature<?, ?>> patchRaspberryBush = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_RASPBERRY_BUSH);
	// static Holder<ConfiguredFeature<?, ?>> patchStrawberryBush = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_STRAWBERRY_BUSH);
	// static Holder<ConfiguredFeature<?, ?>> patchCottonBush = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_COTTON_BUSH);
	// static Holder<ConfiguredFeature<?, ?>> patchPeppercornBush = TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_PEPPERCORN_BUSH);

	public static final ResourceKey<PlacedFeature> BRINE_POOL_PLACED = Technologica.PLACED_FEATURES.register("brine_pool", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.BRINE_POOL_CONFIGURED), List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> NATURAL_GAS_DEPOSIT_PLACED = Technologica.PLACED_FEATURES.register("natural_gas_deposit", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.NATURAL_GAS_DEPOSIT_CONFIGURED), List.of(RarityFilter.onAverageOnceEvery(50), InSquarePlacement.spread(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(6), VerticalAnchor.absolute(30)), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> OASIS_PLACED = Technologica.PLACED_FEATURES.register("oasis", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.OASIS_CONFIGURED), List.of(RarityFilter.onAverageOnceEvery(200), InSquarePlacement.spread(), HeightRangePlacement.uniform(VerticalAnchor.bottom(), VerticalAnchor.absolute(192)), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> OIL_WELL_PLACED = Technologica.PLACED_FEATURES.register("oil_well", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.OIL_WELL_CONFIGURED), List.of(RarityFilter.onAverageOnceEvery(50), InSquarePlacement.spread(), HeightRangePlacement.uniform(VerticalAnchor.aboveBottom(6), VerticalAnchor.absolute(30)), BiomeFilter.biome())));
	// TODO: Can't remember why I left these here. Surely I had a reason for keeping them.
	// public static final ResourceKey<PlacedFeature> PATCH_BLACKBERRY_BUSH_VILLAGE = Technologica.PLACED_FEATURES.register("patch_blackberry_bush");
	// public static final ResourceKey<PlacedFeature> PATCH_BLUEBERRY_BUSH_VILLAGE = Technologica.PLACED_FEATURES.register("patch_blueberry_bush");
	// public static final ResourceKey<PlacedFeature> PATCH_RASPBERRY_BUSH_VILLAGE = Technologica.PLACED_FEATURES.register("patch_raspberry_bush");
	// public static final ResourceKey<PlacedFeature> PATCH_STRAWBERRY_BUSH_VILLAGE = Technologica.PLACED_FEATURES.register("patch_strawberry_bush");
	public static final ResourceKey<PlacedFeature> ORE_SPODUMENE_PLACED = Technologica.PLACED_FEATURES.register("ore_spodumene", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_SPODUMENE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(48), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_BORAX_PLACED = Technologica.PLACED_FEATURES.register("ore_borax", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_BORAX), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(48), VerticalAnchor.absolute(64)))));
	public static final ResourceKey<PlacedFeature> ORE_MAGNESITE_PLACED = Technologica.PLACED_FEATURES.register("ore_magnesite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_MAGNESITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(0), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_BAUXITE_PLACED = Technologica.PLACED_FEATURES.register("ore_bauxite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_BAUXITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_APATITE_PLACED = Technologica.PLACED_FEATURES.register("ore_apatite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_APATITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(48), VerticalAnchor.absolute(64)))));
	public static final ResourceKey<PlacedFeature> ORE_PHOSPHORITE_PLACED = Technologica.PLACED_FEATURES.register("ore_phosphorite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_PHOSPHORITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(32), VerticalAnchor.absolute(48)))));
	public static final ResourceKey<PlacedFeature> ORE_GADOLINITE_PLACED = Technologica.PLACED_FEATURES.register("ore_gadolinite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_GADOLINITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_ILMENITE_PLACED = Technologica.PLACED_FEATURES.register("ore_ilmenite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_ILMENITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.bottom(), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_PATRONITE_PLACED = Technologica.PLACED_FEATURES.register("ore_patronite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_PATRONITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_CHROMITE_PLACED = Technologica.PLACED_FEATURES.register("ore_chromite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_CHROMITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_PYROLUSITE_PLACED = Technologica.PLACED_FEATURES.register("ore_pyrolusite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_PYROLUSITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_COBALTITE_PLACED = Technologica.PLACED_FEATURES.register("ore_cobaltite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_COBALTITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_GARNIERITE_PLACED = Technologica.PLACED_FEATURES.register("ore_garnierite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_GARNIERITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_ARSENOPYRITE_PLACED = Technologica.PLACED_FEATURES.register("ore_arsenopyrite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_ARSENOPYRITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(0), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_CROOKESITE_PLACED = Technologica.PLACED_FEATURES.register("ore_crookesite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_CROOKESITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(0), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_LEPIDOLITE_PLACED = Technologica.PLACED_FEATURES.register("ore_lepidolite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_LEPIDOLITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(0), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_BASTNAESITE_PLACED = Technologica.PLACED_FEATURES.register("ore_bastnaesite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_BASTNAESITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_TANTALITE_PLACED = Technologica.PLACED_FEATURES.register("ore_tantalite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_TANTALITE), commonOrePlacement(16, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(112)))));
	public static final ResourceKey<PlacedFeature> ORE_MOLYBDENITE_PLACED = Technologica.PLACED_FEATURES.register("ore_molybdenite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_MOLYBDENITE), commonOrePlacement(16, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(112)))));
	public static final ResourceKey<PlacedFeature> ORE_PENTLANDITE_PLACED = Technologica.PLACED_FEATURES.register("ore_pentlandite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_PENTLANDITE), commonOrePlacement(10, HeightRangePlacement.triangle(VerticalAnchor.absolute(-24), VerticalAnchor.absolute(56)))));
	public static final ResourceKey<PlacedFeature> ORE_ARGENTITE_PLACED = Technologica.PLACED_FEATURES.register("ore_argentite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_ARGENTITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(-64), VerticalAnchor.absolute(32)))));
	public static final ResourceKey<PlacedFeature> ORE_GALENA_PLACED = Technologica.PLACED_FEATURES.register("ore_galena", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_GALENA), commonOrePlacement(16, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(112)))));
	public static final ResourceKey<PlacedFeature> ORE_SYLVANITE_PLACED = Technologica.PLACED_FEATURES.register("ore_sylvanite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_SYLVANITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(-64), VerticalAnchor.absolute(32)))));
	public static final ResourceKey<PlacedFeature> ORE_CASSITERITE_PLACED = Technologica.PLACED_FEATURES.register("ore_cassiterite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_CASSITERITE), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(0), VerticalAnchor.top()))));
	public static final ResourceKey<PlacedFeature> ORE_WOLFRAMITE_PLACED = Technologica.PLACED_FEATURES.register("ore_wolframite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_WOLFRAMITE), commonOrePlacement(16, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(112)))));
	public static final ResourceKey<PlacedFeature> ORE_OSMIRIDIUM_PLACED = Technologica.PLACED_FEATURES.register("ore_osmiridium", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_OSMIRIDIUM), commonOrePlacement(10, HeightRangePlacement.uniform(VerticalAnchor.absolute(-64), VerticalAnchor.absolute(32)))));
	public static final ResourceKey<PlacedFeature> ORE_PLATINUM_PLACED = Technologica.PLACED_FEATURES.register("ore_platinum", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_PLATINUM), commonOrePlacement(4, HeightRangePlacement.triangle(VerticalAnchor.absolute(-64), VerticalAnchor.absolute(32)))));
	public static final ResourceKey<PlacedFeature> ORE_CINNABAR_PLACED = Technologica.PLACED_FEATURES.register("ore_cinnabar", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_CINNABAR), commonOrePlacement(4, HeightRangePlacement.uniform(VerticalAnchor.bottom(), VerticalAnchor.absolute(15)))));
	public static final ResourceKey<PlacedFeature> ORE_THORIANITE_PLACED = Technologica.PLACED_FEATURES.register("ore_thorianite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_THORIANITE), commonOrePlacement(4, HeightRangePlacement.uniform(VerticalAnchor.bottom(), VerticalAnchor.absolute(15)))));
	public static final ResourceKey<PlacedFeature> ORE_URANINITE_PLACED = Technologica.PLACED_FEATURES.register("ore_uraninite", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_URANINITE), commonOrePlacement(4, HeightRangePlacement.uniform(VerticalAnchor.bottom(), VerticalAnchor.absolute(15)))));
	public static final ResourceKey<PlacedFeature> ORE_EMERALD_PLACED = Technologica.PLACED_FEATURES.register("ore_emerald", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_EMERALD), commonOrePlacement(100, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(480)))));
	public static final ResourceKey<PlacedFeature> ORE_RUBY_PLACED = Technologica.PLACED_FEATURES.register("ore_ruby", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_RUBY), commonOrePlacement(100, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(480)))));
	public static final ResourceKey<PlacedFeature> ORE_SAPPHIRE_PLACED = Technologica.PLACED_FEATURES.register("ore_sapphire", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_SAPPHIRE), commonOrePlacement(100, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(480)))));
	public static final ResourceKey<PlacedFeature> ORE_TOPAZ_PLACED = Technologica.PLACED_FEATURES.register("ore_topaz", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORE_TOPAZ), commonOrePlacement(100, HeightRangePlacement.triangle(VerticalAnchor.absolute(-16), VerticalAnchor.absolute(480)))));
	public static final ResourceKey<PlacedFeature> APRICOT_CHECKED = Technologica.PLACED_FEATURES.register("apricot_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.APRICOT), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.APRICOT_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> ASPEN_CHECKED = Technologica.PLACED_FEATURES.register("aspen_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ASPEN), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.ASPEN_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> AVOCADO_CHECKED = Technologica.PLACED_FEATURES.register("avocado_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.AVOCADO), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.AVOCADO_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> BANANA_CHECKED = Technologica.PLACED_FEATURES.register("banana_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.BANANA), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.BANANA_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> CHERRY_CHECKED = Technologica.PLACED_FEATURES.register("cherry_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.CHERRY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.CHERRY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> CHESTNUT_CHECKED = Technologica.PLACED_FEATURES.register("chestnut_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.CHESTNUT), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.CHESTNUT_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> CINNAMON_CHECKED = Technologica.PLACED_FEATURES.register("cinnamon_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.CINNAMON), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.CINNAMON_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> COCONUT_CHECKED = Technologica.PLACED_FEATURES.register("coconut_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.COCONUT), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.COCONUT_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> EBONY_CHECKED = Technologica.PLACED_FEATURES.register("ebony_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.EBONY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.EBONY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> KIWI_CHECKED = Technologica.PLACED_FEATURES.register("kiwi_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.KIWI), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.KIWI_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> LEMON_CHECKED = Technologica.PLACED_FEATURES.register("lemon_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.LEMON), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.LEMON_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> LIME_CHECKED = Technologica.PLACED_FEATURES.register("lime_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.LIME), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.LIME_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> MAHOGANY_CHECKED = Technologica.PLACED_FEATURES.register("mahogany_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.MAHOGANY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.MAHOGANY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> MAPLE_CHECKED = Technologica.PLACED_FEATURES.register("maple_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.MAPLE), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.MAPLE_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> OLIVE_CHECKED = Technologica.PLACED_FEATURES.register("olive_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.OLIVE), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.OLIVE_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> ORANGE_CHECKED = Technologica.PLACED_FEATURES.register("orange_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ORANGE), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.ORANGE_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> PEACH_CHECKED = Technologica.PLACED_FEATURES.register("peach_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PEACH), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.PEACH_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> PEAR_CHECKED = Technologica.PLACED_FEATURES.register("pear_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PEAR), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.PEAR_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> PLUM_CHECKED = Technologica.PLACED_FEATURES.register("plum_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PLUM), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.PLUM_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> REDWOOD_CHECKED = Technologica.PLACED_FEATURES.register("redwood_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.REDWOOD), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.REDWOOD_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> ROSEWOOD_CHECKED = Technologica.PLACED_FEATURES.register("rosewood_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ROSEWOOD), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.ROSEWOOD_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> RUBBER_CHECKED = Technologica.PLACED_FEATURES.register("rubber_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.RUBBER), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.RUBBER_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> TEAK_CHECKED = Technologica.PLACED_FEATURES.register("teak_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TEAK), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.TEAK_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> WALNUT_CHECKED = Technologica.PLACED_FEATURES.register("walnut_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.WALNUT), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.WALNUT_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> ZEBRAWOOD_CHECKED = Technologica.PLACED_FEATURES.register("zebrawood_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ZEBRAWOOD), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.ZEBRAWOOD_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> ANCIENT_AMBROSIA_CHECKED = Technologica.PLACED_FEATURES.register("ancient_ambrosia_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.ANCIENT_AMBROSIA), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.ANCIENT_AMBROSIA_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> BENEVOLENT_APOTHECARY_CHECKED = Technologica.PLACED_FEATURES.register("benevolent_apothecary_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.BENEVOLENT_APOTHECARY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.BENEVOLENT_APOTHECARY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> CRYOGENIC_SPIRE_CHECKED = Technologica.PLACED_FEATURES.register("cryogenic_spire_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.CRYOGENIC_SPIRE), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.CRYOGENIC_SPIRE_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> MALEVOLENT_APOTHECARY_CHECKED = Technologica.PLACED_FEATURES.register("malevolent_apothecary_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.MALEVOLENT_APOTHECARY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.MALEVOLENT_APOTHECARY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> NECROTIC_CHECKED = Technologica.PLACED_FEATURES.register("necrotic_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.NECROTIC), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.NECROTIC_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> SERENDIPITOUS_APOTHECARY_CHECKED = Technologica.PLACED_FEATURES.register("serendipitous_apothecary_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.SERENDIPITOUS_APOTHECARY), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.SERENDIPITOUS_APOTHECARY_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> THUNDEROUS_CONDUCTOR_CHECKED = Technologica.PLACED_FEATURES.register("thunderous_conductor_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.THUNDEROUS_CONDUCTOR), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.THUNDEROUS_CONDUCTOR_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> TOWERING_INFERNO_CHECKED = Technologica.PLACED_FEATURES.register("towering_inferno_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TOWERING_INFERNO), treePlacement(PlacementUtils.filteredByBlockSurvival(TechnologicaBlocks.TOWERING_INFERNO_SAPLING.get()))));
	public static final ResourceKey<PlacedFeature> OVERGROWTH_CHECKED = Technologica.PLACED_FEATURES.register("overgrowth_checked", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TreeFeatures.TALL_MANGROVE), List.of()));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_SAVANNA_PLACED = Technologica.PLACED_FEATURES.register("trees_zebrawood", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_SAVANNA), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_JUNGLE_PLACED = Technologica.PLACED_FEATURES.register("trees_modified_jungle", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_JUNGLE), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_JUNGLE_EDGE_PLACED = Technologica.PLACED_FEATURES.register("trees_teak", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_JUNGLE_EDGE), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_BAMBOO_JUNGLE_PLACED = Technologica.PLACED_FEATURES.register("trees_bamboo_jungle", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_BAMBOO_JUNGLE), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_FOREST_PLACED = Technologica.PLACED_FEATURES.register("trees_chestnut", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_FOREST), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_BIRCH_FOREST_PLACED = Technologica.PLACED_FEATURES.register("trees_peach", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_BIRCH_FOREST), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_WOODED_HILLS_PLACED = Technologica.PLACED_FEATURES.register("trees_aspen", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_WOODED_HILLS), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_BEACH_PLACED = Technologica.PLACED_FEATURES.register("trees_coconut", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_BEACH), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_TAIGA_PLACED = Technologica.PLACED_FEATURES.register("trees_modified_taiga", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_TAIGA), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_SNOWY_TAIGA_PLACED = Technologica.PLACED_FEATURES.register("trees_snowy_taiga", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_SNOWY_TAIGA), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));
	public static final ResourceKey<PlacedFeature> TREES_MODIFIED_SWAMP_PLACED = Technologica.PLACED_FEATURES.register("trees_orange", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_MODIFIED_SWAMP), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));

	public static final ResourceKey<PlacedFeature> TREES_REDWOOD_FOREST = Technologica.PLACED_FEATURES.register("trees_redwood_forest", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.TREES_REDWOOD_FOREST), vegetationPlacement(PlacementUtils.countExtra(1, 0.1F, 1))));

	public static final ResourceKey<PlacedFeature> PATCH_BLACKBERRY_COMMON_PLACED = Technologica.PLACED_FEATURES.register("patch_blackberry_common", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLACKBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(32), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_BLACKBERRY_RARE_PLACED = Technologica.PLACED_FEATURES.register("patch_blackberry_rare", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLACKBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(384), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_BLUEBERRY_COMMON_PLACED = Technologica.PLACED_FEATURES.register("patch_blueberry_common", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLUEBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(32), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_BLUEBERRY_RARE_PLACED = Technologica.PLACED_FEATURES.register("patch_blueberry_rare", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_BLUEBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(384), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_RASPBERRY_COMMON_PLACED = Technologica.PLACED_FEATURES.register("patch_raspberry_common", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_RASPBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(32), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_RASPBERRY_RARE_PLACED = Technologica.PLACED_FEATURES.register("patch_raspberry_rare", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_RASPBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(384), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_STRAWBERRY_COMMON_PLACED = Technologica.PLACED_FEATURES.register("patch_strawberry_common", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_STRAWBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(32), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_STRAWBERRY_RARE_PLACED = Technologica.PLACED_FEATURES.register("patch_strawberry_rare", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_STRAWBERRY_BUSH), List.of(RarityFilter.onAverageOnceEvery(384), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_COTTON_PLACED = Technologica.PLACED_FEATURES.register("patch_cotton", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_COTTON_BUSH), List.of(RarityFilter.onAverageOnceEvery(32), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> PATCH_PEPPERCORNS_PLACED = Technologica.PLACED_FEATURES.register("patch_peppercorns", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.PATCH_PEPPERCORN_BUSH), List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome())));

	public static final ResourceKey<PlacedFeature> OVERGROWTH_PLACED = Technologica.PLACED_FEATURES.register("overgrowth_placed", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(VegetationFeatures.MANGROVE_VEGETATION), List.of(CountOnEveryLayerPlacement.of(6), BiomeFilter.biome())));

	public static final ResourceKey<PlacedFeature> NAVAL_MINE = Technologica.PLACED_FEATURES.register("naval_mine", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.NAVAL_MINE), List.of(CountOnEveryLayerPlacement.of(UniformInt.of(0, 8)), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> DEEP_CORALS = Technologica.PLACED_FEATURES.register("deep_corals", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(AquaticFeatures.WARM_OCEAN_VEGETATION), List.of(CountOnEveryLayerPlacement.of(16), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> DEEP_KELP = Technologica.PLACED_FEATURES.register("deep_kelp", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.DEEP_KELP), List.of(CountOnEveryLayerPlacement.of(16), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> DEEP_SEAGRASS = Technologica.PLACED_FEATURES.register("deep_seagrass", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.DEEP_SEAGRASS), List.of(CountOnEveryLayerPlacement.of(64), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> DEEP_BASALT_PILLAR = Technologica.PLACED_FEATURES.register("deep_basalt_pillar", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.DEEP_BASALT_PILLAR), List.of(CountPlacement.of(200), InSquarePlacement.spread(), PlacementUtils.FULL_RANGE, BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> HYDROTHERMAL_VENT = Technologica.PLACED_FEATURES.register("hydrothermal_vent", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.HYDROTHERMAL_VENT), List.of(InSquarePlacement.spread(), RarityFilter.onAverageOnceEvery(4), BoundedHeightmap.of(0, 18, ConstantInt.of(1)), BiomeFilter.biome())));
	public static final ResourceKey<PlacedFeature> DEEP_BASALT_BLOB = Technologica.PLACED_FEATURES.register("deep_basalt_blob", () -> new PlacedFeature(TLReGenWorldgenPlacedFeature.bootstrapContext.lookup(Registries.CONFIGURED_FEATURE).getOrThrow(TechnologicaConfiguredFeatures.DEEP_BASALT_BLOB), List.of(CountPlacement.of(50), InSquarePlacement.spread(), PlacementUtils.FULL_RANGE, BiomeFilter.biome())));

	protected static List<PlacementModifier> commonOrePlacement(int p_195344_, PlacementModifier p_195345_) {
		return orePlacement(CountPlacement.of(p_195344_), p_195345_);
	}

	private static List<PlacementModifier> orePlacement(PlacementModifier p_195347_, PlacementModifier p_195348_) {
		return List.of(p_195347_, InSquarePlacement.spread(), p_195348_, BiomeFilter.biome());
	}

	protected static List<PlacementModifier> treePlacement(PlacementModifier p_195345_) {
		return List.of(p_195345_);
	}

	private static ImmutableList.Builder<PlacementModifier> treePlacementBase(PlacementModifier p_195485_) {
		return ImmutableList.<PlacementModifier>builder().add(p_195485_).add(InSquarePlacement.spread()).add(SurfaceWaterDepthFilter.forMaxDepth(0)).add(PlacementUtils.HEIGHTMAP_OCEAN_FLOOR).add(BiomeFilter.biome());
	}

	public static List<PlacementModifier> vegetationPlacement(PlacementModifier p_195480_) {
		return treePlacementBase(p_195480_).build();
	}
}
