package com.technologica.registration.dynamic;

import java.util.List;

import com.mojang.datafixers.util.Pair;
import com.technologica.Technologica;
import com.technologica.registration.deferred.TechnologicaEntityTypes;
import com.technologica.world.entity.TechnologicaMobCategory;
import com.tlregen.api.resourcegen.util.helpers.TLReGenBiomeHelper;
import com.tlregen.api.resourcegen.util.helpers.TLReGenBiomeHelper.TLReGenCarvers;
import com.tlregen.api.resourcegen.util.helpers.TLReGenBiomeHelper.TLReGenEffects;
import com.tlregen.api.resourcegen.util.helpers.TLReGenBiomeHelper.TLReGenFeatures;
import com.tlregen.api.resourcegen.util.helpers.TLReGenBiomeHelper.TLReGenSpawners;

import net.minecraft.data.worldgen.Carvers;
import net.minecraft.data.worldgen.placement.CavePlacements;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.biome.AmbientMoodSettings;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.BiomeSpecialEffects;
import net.minecraft.world.level.biome.MobSpawnSettings;

public final class TechnologicaBiomes {
	public static final ResourceKey<Biome> SILENT_EXPANSES = Technologica.BIOMES.register("silent_expanses", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 0.0F, new TLReGenEffects(0, 10387789, 9470285, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0, 4159204, 329011), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(TechnologicaEntityTypes.SWEEPER.get(), 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 2.0F));
	public static final ResourceKey<Biome> CRATER_FIELDS = Technologica.BIOMES.register("crater_fields", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 0.6F, new TLReGenEffects(0, 10387789, 9470285, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0, 4159204, 329011), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), true, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.CREEPER, 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 0.6F));
	public static final ResourceKey<Biome> SHATTERED_CORRIDORS = Technologica.BIOMES.register("shattered_corridors", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 0.0F, new TLReGenEffects(0, 10387789, 9470285, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0, 4159204, 329011), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(TechnologicaEntityTypes.PEEPER.get(), 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 2.0F));
	public static final ResourceKey<Biome> MISTY_MIRE = Technologica.BIOMES.register("misty_mire", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 0.5F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 8103167, 4445678, 270131), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.OVERGROWTH_PLACED), List.of()), true, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.HUSK, 1, 1, 1), new MobSpawnSettings.SpawnerData(EntityType.SLIME, 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 0.5F));
	public static final ResourceKey<Biome> BRAMBLE = Technologica.BIOMES.register("bramble", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 0.5F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 8103167, 4445678, 270131), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.OVERGROWTH_PLACED), List.of()), true, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.HUSK, 1, 1, 1), new MobSpawnSettings.SpawnerData(EntityType.SLIME, 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 0.5F));
	public static final ResourceKey<Biome> RUSTING_GROUNDS = Technologica.BIOMES.register("rusting_grounds", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(0x032433, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0x032433, 0x032433, 0x032433), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.NAVAL_MINE), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(Pair.of(TechnologicaMobCategory.SHARK, List.of(new MobSpawnSettings.SpawnerData(TechnologicaEntityTypes.SHARK.get(), 1, 1, 1))))), 0.5F));
	public static final ResourceKey<Biome> FORGOTTEN_REEF = Technologica.BIOMES.register("forgotten_reef", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 8103167, 0x43D5EE, 0x41F33), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.DEEP_CORALS), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.TROPICAL_FISH, 1, 1, 15), new MobSpawnSettings.SpawnerData(EntityType.PUFFERFISH, 1, 1, 3)), List.of(new MobSpawnSettings.SpawnerData(EntityType.SQUID, 1, 1, 1)), List.of()), 0.5F));
	public static final ResourceKey<Biome> NAVAL_GRAVEYARD = Technologica.BIOMES.register("naval_graveyard", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(0x0e151d, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0x0e151d, 0x0e151d, 0x0e151d), new TLReGenFeatures(List.of(), List.of(), List.of(CavePlacements.LARGE_DRIPSTONE, CavePlacements.POINTED_DRIPSTONE), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), 0.5F));
	public static final ResourceKey<Biome> SUNKEN_FOREST = Technologica.BIOMES.register("sunken_forest", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0, 0x3A7A6A, 0x4D7A60), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.DEEP_KELP, TechnologicaPlacedFeatures.DEEP_SEAGRASS), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.TURTLE, 1, 1, 1)), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), 0.5F));
	public static final ResourceKey<Biome> HYDROTHERMAL_CAVERN = Technologica.BIOMES.register("hydrothermal_cavern", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(0x262338, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 0x262338, 0x262338, 0x262338), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.DEEP_BASALT_PILLAR, TechnologicaPlacedFeatures.HYDROTHERMAL_VENT), List.of(), List.of(CavePlacements.UNDERWATER_MAGMA), List.of(TechnologicaPlacedFeatures.DEEP_BASALT_BLOB), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), 0.5F));
	public static final ResourceKey<Biome> ECHOSCAPE = Technologica.BIOMES.register("echoscape", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(), List.of()), 1.0F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 8103167, 0x3D57D6, 0x050533), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of()), false, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.DOLPHIN, 1, 1, 1)), List.of()), 0.5F));
	public static final ResourceKey<Biome> REDWOOD_FOREST = Technologica.BIOMES.register("redwood_forest", () -> TLReGenBiomeHelper.biome(new TLReGenCarvers(List.of(Carvers.CAVE, Carvers.CAVE_EXTRA_UNDERGROUND, Carvers.CANYON), List.of()), 0.8F, new TLReGenEffects(12638463, 9285927, BiomeSpecialEffects.GrassColorModifier.SWAMP, AmbientMoodSettings.LEGACY_CAVE_SETTINGS, 8037887, 4159204, 329011), new TLReGenFeatures(List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(TechnologicaPlacedFeatures.TREES_REDWOOD_FOREST), List.of()), true, new TLReGenSpawners(List.of(), List.of(), List.of(), List.of(), List.of(new MobSpawnSettings.SpawnerData(EntityType.HUSK, 1, 1, 1), new MobSpawnSettings.SpawnerData(EntityType.SLIME, 1, 1, 1)), List.of(), List.of(), List.of(), List.of()), 0.5F));
}
