package com.technologica.client.renderer.entity;

import java.util.Map;

import org.joml.Vector3f;

import com.google.common.collect.Maps;
import com.technologica.client.model.AlligatorModel;
import com.technologica.client.model.AxemanModel;
import com.technologica.client.model.BeaverModel;
import com.technologica.client.model.BuffaloModel;
import com.technologica.client.model.CobraModel;
import com.technologica.client.model.CottonmouthModel;
import com.technologica.client.model.CrabModel;
import com.technologica.client.model.DeerModel;
import com.technologica.client.model.ElephantModel;
import com.technologica.client.model.GiraffeModel;
import com.technologica.client.model.GorillaModel;
import com.technologica.client.model.JaguarModel;
import com.technologica.client.model.KingCrabModel;
import com.technologica.client.model.LeopardSealModel;
import com.technologica.client.model.LionModel;
import com.technologica.client.model.LizardModel;
import com.technologica.client.model.MooseModel;
import com.technologica.client.model.NarwhalModel;
import com.technologica.client.model.OctopusModel;
import com.technologica.client.model.OstrichModel;
import com.technologica.client.model.PenguinModel;
import com.technologica.client.model.RaccoonModel;
import com.technologica.client.model.SharkModel;
import com.technologica.client.model.SlothModel;
import com.technologica.client.model.StingrayModel;
import com.technologica.client.model.VultureModel;
import com.technologica.client.model.WalrusModel;
import com.technologica.client.model.geom.TechnologicaModelLayers;
import com.technologica.client.renderer.entity.decoration.InvisibleRenderer;
import com.technologica.client.renderer.entity.item.NavalMineRenderer;
import com.technologica.client.renderer.entity.layers.AxemanEyesLayer;
import com.technologica.client.renderer.entity.layers.MummyEyesLayer;
import com.technologica.client.renderer.entity.layers.RaccoonHeldItemLayer;
import com.technologica.client.renderer.entity.layers.ZebraArmorLayer;
import com.technologica.client.renderer.entity.magic.MagicLightningBoltRenderer;
import com.technologica.client.renderer.entity.mob.AtomicCreeperRenderer;
import com.technologica.client.renderer.entity.mob.CoyoteRenderer;
import com.technologica.client.renderer.entity.mob.DuckRenderer;
import com.technologica.client.renderer.entity.mob.DustDevilRenderer;
import com.technologica.client.renderer.entity.mob.FigureEightPufferfishRenderer;
import com.technologica.client.renderer.entity.mob.FlamingoRenderer;
import com.technologica.client.renderer.entity.mob.OwlRenderer;
import com.technologica.client.renderer.entity.mob.PiranhaRenderer;
import com.technologica.client.renderer.entity.mob.PoisonDartFrogRenderer;
import com.technologica.client.renderer.entity.mob.ScorpionRenderer;
import com.technologica.client.renderer.entity.mob.TechnologicaMobRenderer;
import com.technologica.client.renderer.entity.mob.TechnologicaMobTextures;
import com.technologica.client.renderer.entity.mob.TurkeyRenderer;
import com.technologica.client.renderer.entity.projectile.HarpoonRenderer;
import com.technologica.client.renderer.entity.projectile.ThrownSpearRenderer;
import com.technologica.client.renderer.entity.vehicle.SubmersibleRenderer;
import com.technologica.client.renderer.entity.vehicle.TechnologicaBoatRenderer;
import com.technologica.registration.deferred.TechnologicaEntityTypes;
import com.technologica.world.entity.animal.Alligator;
import com.technologica.world.entity.animal.Beaver;
import com.technologica.world.entity.animal.Buffalo;
import com.technologica.world.entity.animal.Cobra;
import com.technologica.world.entity.animal.Cottonmouth;
import com.technologica.world.entity.animal.Crab;
import com.technologica.world.entity.animal.Deer;
import com.technologica.world.entity.animal.Elephant;
import com.technologica.world.entity.animal.Giraffe;
import com.technologica.world.entity.animal.Gorilla;
import com.technologica.world.entity.animal.GrizzlyBear;
import com.technologica.world.entity.animal.Jaguar;
import com.technologica.world.entity.animal.KingCrab;
import com.technologica.world.entity.animal.LeopardSeal;
import com.technologica.world.entity.animal.Lion;
import com.technologica.world.entity.animal.Lizard;
import com.technologica.world.entity.animal.Moose;
import com.technologica.world.entity.animal.Narwhal;
import com.technologica.world.entity.animal.Octopus;
import com.technologica.world.entity.animal.Ostrich;
import com.technologica.world.entity.animal.Penguin;
import com.technologica.world.entity.animal.Raccoon;
import com.technologica.world.entity.animal.Shark;
import com.technologica.world.entity.animal.Sloth;
import com.technologica.world.entity.animal.Stingray;
import com.technologica.world.entity.animal.Vulture;
import com.technologica.world.entity.animal.Walrus;
import com.technologica.world.entity.animal.Zebra;
import com.technologica.world.entity.monster.Axeman;
import com.technologica.world.entity.monster.Beeper;
import com.technologica.world.entity.monster.Mummy;
import com.technologica.world.entity.monster.Peeper;
import com.technologica.world.entity.monster.Sleeper;
import com.technologica.world.entity.monster.Sweeper;
import com.technologica.world.entity.monster.Weeper;

import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.HorseModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.ZombieModel;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;

public class TechnologicaEntityRenderers {
	public static final Map<EntityType<? extends Entity>, EntityRendererProvider<Entity>> PROVIDERS = Maps.newHashMap();

	static {
		register(TechnologicaEntityTypes.ALLIGATOR.get(), context -> new TechnologicaMobRenderer<Alligator, AlligatorModel<Alligator>>(context, new AlligatorModel<>(context.bakeLayer(TechnologicaModelLayers.ALLIGATOR)), TechnologicaMobTextures.ALLIGATOR, 0.6F));
		register(TechnologicaEntityTypes.ATOMIC_CREEPER.get(), AtomicCreeperRenderer::new);
		register(TechnologicaEntityTypes.AXEMAN.get(), context -> new TechnologicaMobRenderer<Axeman, AxemanModel<Axeman>>(context, new AxemanModel<>(context.bakeLayer(TechnologicaModelLayers.AXEMAN)), TechnologicaMobTextures.AXEMAN, 0.7F, renderer -> renderer.addLayer(new AxemanEyesLayer<>(renderer))));
		register(TechnologicaEntityTypes.BEAVER.get(), context -> new TechnologicaMobRenderer<Beaver, BeaverModel<Beaver>>(context, new BeaverModel<>(context.bakeLayer(TechnologicaModelLayers.BEAVER)), TechnologicaMobTextures.BEAVER, 0.3F));
		register(TechnologicaEntityTypes.BEEPER.get(), context -> new TechnologicaMobRenderer<Beeper, CreeperModel<Beeper>>(context, new CreeperModel<>(context.bakeLayer(TechnologicaModelLayers.BEEPER)), TechnologicaMobTextures.BEEPER, 0.5F));
		register(TechnologicaEntityTypes.BUFFALO.get(), context -> new TechnologicaMobRenderer<Buffalo, BuffaloModel<Buffalo>>(context, new BuffaloModel<>(context.bakeLayer(TechnologicaModelLayers.BUFFALO)), TechnologicaMobTextures.BUFFALO, 0.9F));
		register(TechnologicaEntityTypes.COBRA.get(), context -> new TechnologicaMobRenderer<Cobra, CobraModel<Cobra>>(context, new CobraModel<>(context.bakeLayer(TechnologicaModelLayers.COBRA)), TechnologicaMobTextures.COBRA, 0.1F));
		register(TechnologicaEntityTypes.COCONUT.get(), context -> new ThrownItemRenderer<>(context, 1.0F, true));
		register(TechnologicaEntityTypes.COTTONMOUTH.get(), context -> new TechnologicaMobRenderer<Cottonmouth, CottonmouthModel<Cottonmouth>>(context, new CottonmouthModel<>(context.bakeLayer(TechnologicaModelLayers.COTTONMOUTH)), TechnologicaMobTextures.COTTONMOUTH, 0.1F));
		register(TechnologicaEntityTypes.COYOTE.get(), CoyoteRenderer::new);
		register(TechnologicaEntityTypes.CRAB.get(), context -> new TechnologicaMobRenderer<Crab, CrabModel<Crab>>(context, new CrabModel<>(context.bakeLayer(TechnologicaModelLayers.CRAB)), TechnologicaMobTextures.CRAB, 0.3F));
		register(TechnologicaEntityTypes.DEER.get(), context -> new TechnologicaMobRenderer<Deer, DeerModel<Deer>>(context, new DeerModel<>(context.bakeLayer(TechnologicaModelLayers.DEER)), TechnologicaMobTextures.DEER, 0.6F));
		register(TechnologicaEntityTypes.DODGEBALL.get(), context -> new ThrownItemRenderer<>(context, 1.0F, true));
		register(TechnologicaEntityTypes.DUCK.get(), DuckRenderer::new);
		register(TechnologicaEntityTypes.DUST_DEVIL.get(), DustDevilRenderer::new);
		register(TechnologicaEntityTypes.ELEPHANT.get(), context -> new TechnologicaMobRenderer<Elephant, ElephantModel<Elephant>>(context, new ElephantModel<>(context.bakeLayer(TechnologicaModelLayers.ELEPHANT)), TechnologicaMobTextures.ELEPHANT, 1.8F));
		register(TechnologicaEntityTypes.FLAMINGO.get(), FlamingoRenderer::new);
		register(TechnologicaEntityTypes.FIGURE_EIGHT_PUFFERFISH.get(), FigureEightPufferfishRenderer::new);
		register(TechnologicaEntityTypes.GIRAFFE.get(), context -> new TechnologicaMobRenderer<Giraffe, GiraffeModel<Giraffe>>(context, new GiraffeModel<>(context.bakeLayer(TechnologicaModelLayers.GIRAFFE)), TechnologicaMobTextures.GIRAFFE, 0.8F));
		register(TechnologicaEntityTypes.GORILLA.get(), context -> new TechnologicaMobRenderer<Gorilla, GorillaModel<Gorilla>>(context, new GorillaModel<>(context.bakeLayer(TechnologicaModelLayers.GORILLA)), TechnologicaMobTextures.GORILLA, 0.7F));
		register(TechnologicaEntityTypes.GRIZZLY_BEAR.get(), context -> new TechnologicaMobRenderer<GrizzlyBear, PolarBearModel<GrizzlyBear>>(context, new PolarBearModel<>(context.bakeLayer(TechnologicaModelLayers.GRIZZLY_BEAR)), TechnologicaMobTextures.GRIZZLY_BEAR, 0.8F, new Vector3f(1.1F, 1.1F, 1.1F)));
		register(TechnologicaEntityTypes.HARPOON.get(), HarpoonRenderer::new);
		register(TechnologicaEntityTypes.INVISIBLE_SEAT.get(), InvisibleRenderer::new);
		register(TechnologicaEntityTypes.JAGUAR.get(), context -> new TechnologicaMobRenderer<Jaguar, JaguarModel<Jaguar>>(context, new JaguarModel<>(context.bakeLayer(TechnologicaModelLayers.JAGUAR)), TechnologicaMobTextures.JAGUAR, 0.6F));
		register(TechnologicaEntityTypes.KING_CRAB.get(), context -> new TechnologicaMobRenderer<KingCrab, KingCrabModel<KingCrab>>(context, new KingCrabModel<>(context.bakeLayer(TechnologicaModelLayers.KING_CRAB)), TechnologicaMobTextures.KING_CRAB, 0.4F));
		register(TechnologicaEntityTypes.LEOPARD_SEAL.get(), context -> new TechnologicaMobRenderer<LeopardSeal, LeopardSealModel<LeopardSeal>>(context, new LeopardSealModel<>(context.bakeLayer(TechnologicaModelLayers.LEOPARD_SEAL)), TechnologicaMobTextures.LEOPARD_SEAL, 0.5F));
		register(TechnologicaEntityTypes.LION.get(), context -> new TechnologicaMobRenderer<Lion, LionModel<Lion>>(context, new LionModel<>(context.bakeLayer(TechnologicaModelLayers.LION)), TechnologicaMobTextures.LION, 0.7F));
		register(TechnologicaEntityTypes.LIZARD.get(), context -> new TechnologicaMobRenderer<Lizard, LizardModel<Lizard>>(context, new LizardModel<>(context.bakeLayer(TechnologicaModelLayers.LIZARD)), TechnologicaMobTextures.LIZARD, 0.2F));
		register(TechnologicaEntityTypes.MAGIC_LIGHTNING.get(), MagicLightningBoltRenderer::new);
		register(TechnologicaEntityTypes.METEOR.get(), context -> new ThrownItemRenderer<>(context, 4.0F, true));
		register(TechnologicaEntityTypes.MOOSE.get(), context -> new TechnologicaMobRenderer<Moose, MooseModel<Moose>>(context, new MooseModel<>(context.bakeLayer(TechnologicaModelLayers.MOOSE)), TechnologicaMobTextures.MOOSE, 1.1F));
		register(TechnologicaEntityTypes.MUMMY.get(), context -> new TechnologicaMobRenderer<Mummy, ZombieModel<Mummy>>(context, new ZombieModel<>(context.bakeLayer(TechnologicaModelLayers.MUMMY)), TechnologicaMobTextures.MUMMY, 0.5F, renderer -> renderer.addLayer(new MummyEyesLayer<>(renderer))));
		register(TechnologicaEntityTypes.NARWHAL.get(), context -> new TechnologicaMobRenderer<Narwhal, NarwhalModel<Narwhal>>(context, new NarwhalModel<>(context.bakeLayer(TechnologicaModelLayers.NARWHAL)), TechnologicaMobTextures.NARWHAL, 0.5F));
		register(TechnologicaEntityTypes.NAVAL_MINE.get(), NavalMineRenderer::new);
		register(TechnologicaEntityTypes.OCTOPUS.get(), context -> new TechnologicaMobRenderer<Octopus, OctopusModel<Octopus>>(context, new OctopusModel<>(context.bakeLayer(TechnologicaModelLayers.OCTOPUS)), TechnologicaMobTextures.OCTOPUS, 0.5F));
		register(TechnologicaEntityTypes.OSTRICH.get(), context -> new TechnologicaMobRenderer<Ostrich, OstrichModel<Ostrich>>(context, new OstrichModel<>(context.bakeLayer(TechnologicaModelLayers.OSTRICH)), TechnologicaMobTextures.OSTRICH, 0.5F));
		register(TechnologicaEntityTypes.OWL.get(), OwlRenderer::new);
		register(TechnologicaEntityTypes.PEEPER.get(), context -> new TechnologicaMobRenderer<Peeper, CreeperModel<Peeper>>(context, new CreeperModel<>(context.bakeLayer(TechnologicaModelLayers.PEEPER)), TechnologicaMobTextures.PEEPER, 0.5F));
		register(TechnologicaEntityTypes.PENGUIN.get(), context -> new TechnologicaMobRenderer<Penguin, PenguinModel<Penguin>>(context, new PenguinModel<>(context.bakeLayer(TechnologicaModelLayers.PENGUIN)), TechnologicaMobTextures.PENGUIN, 0.3F));
		register(TechnologicaEntityTypes.PIRANHA.get(), PiranhaRenderer::new);
		register(TechnologicaEntityTypes.POISON_DART_FROG.get(), PoisonDartFrogRenderer::new);
		register(TechnologicaEntityTypes.RACCOON.get(), context -> new TechnologicaMobRenderer<Raccoon, RaccoonModel<Raccoon>>(context, new RaccoonModel<>(context.bakeLayer(TechnologicaModelLayers.RACCOON)), TechnologicaMobTextures.RACCOON, 0.4F, renderer -> renderer.addLayer(new RaccoonHeldItemLayer(renderer))));
		register(TechnologicaEntityTypes.SCORPION.get(), ScorpionRenderer::new);
		register(TechnologicaEntityTypes.SHARK.get(), context -> new TechnologicaMobRenderer<Shark, SharkModel<Shark>>(context, new SharkModel<>(context.bakeLayer(TechnologicaModelLayers.SHARK)), TechnologicaMobTextures.SHARK, 0.7F));
		register(TechnologicaEntityTypes.SLEEPER.get(), context -> new TechnologicaMobRenderer<Sleeper, CreeperModel<Sleeper>>(context, new CreeperModel<>(context.bakeLayer(TechnologicaModelLayers.SLEEPER)), TechnologicaMobTextures.SLEEPER, 0.5F));
		register(TechnologicaEntityTypes.SLOTH.get(), context -> new TechnologicaMobRenderer<Sloth, SlothModel<Sloth>>(context, new SlothModel<>(context.bakeLayer(TechnologicaModelLayers.SLOTH)), TechnologicaMobTextures.SLOTH, 0.4F));
		register(TechnologicaEntityTypes.SPEAR.get(), ThrownSpearRenderer::new);
		register(TechnologicaEntityTypes.STINGRAY.get(), context -> new TechnologicaMobRenderer<Stingray, StingrayModel<Stingray>>(context, new StingrayModel<>(context.bakeLayer(TechnologicaModelLayers.STINGRAY)), TechnologicaMobTextures.STINGRAY, 0.5F));
		register(TechnologicaEntityTypes.SUBMERSIBLE.get(), context -> new SubmersibleRenderer(context));
		register(TechnologicaEntityTypes.SWEEPER.get(), context -> new TechnologicaMobRenderer<Sweeper, CreeperModel<Sweeper>>(context, new CreeperModel<>(context.bakeLayer(TechnologicaModelLayers.SWEEPER)), TechnologicaMobTextures.SWEEPER, 0.5F));
		register(TechnologicaEntityTypes.TECHNOLOGICA_BOAT.get(), context -> new TechnologicaBoatRenderer(context, false));
		register(TechnologicaEntityTypes.TURKEY.get(), TurkeyRenderer::new);
		register(TechnologicaEntityTypes.VULTURE.get(), context -> new TechnologicaMobRenderer<Vulture, VultureModel<Vulture>>(context, new VultureModel<>(context.bakeLayer(TechnologicaModelLayers.VULTURE)), TechnologicaMobTextures.VULTURE, 0.5F));
		register(TechnologicaEntityTypes.WALRUS.get(), context -> new TechnologicaMobRenderer<Walrus, WalrusModel<Walrus>>(context, new WalrusModel<>(context.bakeLayer(TechnologicaModelLayers.WALRUS)), TechnologicaMobTextures.WALRUS, 0.8F));
		register(TechnologicaEntityTypes.WEEPER.get(), context -> new TechnologicaMobRenderer<Weeper, CreeperModel<Weeper>>(context, new CreeperModel<>(context.bakeLayer(TechnologicaModelLayers.WEEPER)), TechnologicaMobTextures.WEEPER, 0.5F));
		register(TechnologicaEntityTypes.ZEBRA.get(), context -> new TechnologicaMobRenderer<Zebra, HorseModel<Zebra>>(context, new HorseModel<>(context.bakeLayer(TechnologicaModelLayers.ZEBRA)), TechnologicaMobTextures.ZEBRA, 0.5F, new Vector3f(1.1F, 1.1F, 1.1F), renderer -> renderer.addLayer(new ZebraArmorLayer(renderer, context.getModelSet()))));
	}

	@SuppressWarnings("unchecked")
	public static <T extends Entity> void register(EntityType<? extends T> entity, EntityRendererProvider<T> renderer) {
		PROVIDERS.put((EntityType<? extends T>) entity, (EntityRendererProvider<Entity>) renderer);
	}
}
