package com.technologica.client.model;

import java.util.List;

import com.technologica.util.text.TechnologicaLocation;

import net.minecraft.resources.ResourceLocation;

public class AdditionalModels {
	public static final List<ResourceLocation> MODELS = List.of(new TechnologicaLocation("item/technetium_ingot_base"), new TechnologicaLocation("item/promethium_ingot_base"), new TechnologicaLocation("item/polonium_ingot_base"), new TechnologicaLocation("item/francium_ingot_base"), new TechnologicaLocation("item/radium_ingot_base"), new TechnologicaLocation("item/actinium_ingot_base"), new TechnologicaLocation("item/thorium_ingot_base"), new TechnologicaLocation("item/protactinium_ingot_base"), new TechnologicaLocation("item/uranium_ingot_base"), new TechnologicaLocation("item/neptunium_ingot_base"), new TechnologicaLocation("item/plutonium_ingot_base"), new TechnologicaLocation("item/americium_ingot_base"), new TechnologicaLocation("item/curium_ingot_base"), new TechnologicaLocation("item/berkelium_ingot_base"), new TechnologicaLocation("item/californium_ingot_base"), new TechnologicaLocation("item/einsteinium_ingot_base"), new TechnologicaLocation("item/fermium_ingot_base"), new TechnologicaLocation("item/mendelevium_ingot_base"), new TechnologicaLocation("item/nobelium_ingot_base"), new TechnologicaLocation("item/lawrencium_ingot_base"), new TechnologicaLocation("item/rutherfordium_ingot_base"), new TechnologicaLocation("item/dubnium_ingot_base"), new TechnologicaLocation("item/seaborgium_ingot_base"), new TechnologicaLocation("item/bohrium_ingot_base"), new TechnologicaLocation("item/hassium_ingot_base"), new TechnologicaLocation("item/meitnerium_ingot_base"), new TechnologicaLocation("item/darmstadtium_ingot_base"), new TechnologicaLocation("item/roentgenium_ingot_base"), new TechnologicaLocation("item/copernicium_ingot_base"), new TechnologicaLocation("item/nihonium_ingot_base"), new TechnologicaLocation("item/flevorium_ingot_base"), new TechnologicaLocation("item/moscovium_ingot_base"), new TechnologicaLocation("item/livermorium_ingot_base"), new TechnologicaLocation("item/tennessine_ingot_base"), new TechnologicaLocation("item/oganesson_ingot_base"), new TechnologicaLocation("item/astatine_chunk_base"), new TechnologicaLocation("item/excitation_of_strike_base"), new TechnologicaLocation("item/ignition_of_combustion_base"), new TechnologicaLocation("item/submersion_of_suppression_base"));
}
